# Site settings
title: byronosaur
description: "blog and projects about various topics in biology"
baseurl: ""
# email: your-email@domain.com
# url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
# don't publish posts with future date in their front matter
future: false
